In [2]:
import pandas as pd

In [23]:
data = pd.read_csv('data/alturas-pesos-train.csv')

In [26]:
data

      Genero  Peso  Altura
0      Mujer    54     155
1     Hombre    94     189
2     Hombre    91     174
3      Mujer    60     167
4      Mujer    72     170
5      Mujer    58     157
6      Mujer    67     165
7      Mujer    70     174
8     Hombre    69     167
9     Hombre    87     178
10     Mujer    62     159
11    Hombre    78     166
12    Hombre    87     169
13     Mujer    74     165
14     Mujer    63     162
15     Mujer    60     164
16     Mujer    62     158
17     Mujer    62     164
18    Hombre    97     185
19     Mujer    63     161
20     Mujer    66     157
21     Mujer    53     162
22     Mujer    55     161
23     Mujer    58     160
24     Mujer    73     169
25     Mujer    38     142
26    Hombre    78     174
27     Mujer    52     151
28    Hombre    88     178
29    Hombre    86     179
...      ...   ...     ...
7970  Hombre    89     182
7971  Hombre    70     170
7972   Mujer    68     170
7973  Hombre    84     174
7974  Hombre    76     169
7975   Mujer    71     169
7976  Hombre    89     180
7977   Mujer    59     169
7978   Mujer    59     159
7979   Mujer    46     150
7980  Hombre    91     178
7981  Hombre    62     157
7982  Hombre    73     169
7983   Mujer    50     151
7984   Mujer    65     163
7985   Mujer    54     154
7986  Hombre    83     176
7987   Mujer    64     168
7988  Hombre    82     166
7989  Hombre    95     186
7990   Mujer    58     165
7991   Mujer    66     167
7992  Hombre    78     175
7993  Hombre    88     170
7994   Mujer    67     160
7995   Mujer    63     160
7996   Mujer    41     149
7997   Mujer    71     163
7998  Hombre    81     175
7999   Mujer    68     171

[8000 rows x 3 columns]

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
model = LinearRegression()

In [63]:
data[['Altura']].values

array([[155],
       [189],
       [174],
       ...,
       [163],
       [175],
       [171]])

In [66]:
model.fit(data[['Altura']].values, data[['Peso']].values)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [68]:
print(model.intercept_, model.coef_)

[-158.39556463] [[1.37500931]]

In [69]:
model.predict(171)

array([[76.73102742]])